package BookManagement;

import javax.swing.JOptionPane;

/**
 *
 * @author Quốc Hùng
 */
public class AddNewBao extends javax.swing.JFrame {
    FunctionHandling handle;
    /**
     * Creates new form AddNewBao
     */
    public AddNewBao() {
        handle = new FunctionHandling();
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        themSachButton = new javax.swing.JButton();
        maTLBaoTF = new javax.swing.JTextField();
        huyBoSachButton = new javax.swing.JButton();
        tenNSBBaoTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        soBanPhatHanhBaoTF = new javax.swing.JTextField();
        ngayPhatHanhBaoTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Mã Tài Liệu:");

        jLabel3.setText("Số bản Phát Hành:");

        jLabel4.setText("Tên Nhà Xuất Bản:");

        themSachButton.setText("Thêm");
        themSachButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themSachButtonActionPerformed(evt);
            }
        });

        huyBoSachButton.setText("Huỷ Bỏ");
        huyBoSachButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                huyBoSachButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thêm mới");

        jLabel6.setText("Ngày Phát Hành:");

        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("VD: 20-10-2003");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(themSachButton)
                .addGap(49, 49, 49)
                .addComponent(huyBoSachButton)
                .addGap(16, 16, 16))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ngayPhatHanhBaoTF)
                            .addComponent(maTLBaoTF)
                            .addComponent(tenNSBBaoTF)
                            .addComponent(soBanPhatHanhBaoTF, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maTLBaoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tenNSBBaoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(soBanPhatHanhBaoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ngayPhatHanhBaoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(themSachButton)
                    .addComponent(huyBoSachButton))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void themSachButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themSachButtonActionPerformed
        if(maTLBaoTF.getText().equals("") ||
            tenNSBBaoTF.getText().equals("") ||
            soBanPhatHanhBaoTF.getText().equals("") ||
            ngayPhatHanhBaoTF.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "bạn cần nhập tất cả các trường!",
                "Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }

        for(Bao bao : handle.GetDataBao()) {
            if(maTLBaoTF.getText().equals(bao.getMaTaiLieu())) {
                JOptionPane.showMessageDialog(rootPane, "Mã tài liệu này hiện đã tồn tại!! ",
                    "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

        Bao bao = new Bao();
        bao.setMaTaiLieu(maTLBaoTF.getText());
        bao.setTenNSB(tenNSBBaoTF.getText());
        bao.setSoBanPhatHanh(Integer.valueOf(soBanPhatHanhBaoTF.getText()));
        bao.setNgayPhatHanh(ngayPhatHanhBaoTF.getText());

        handle.AddNewBao(bao);

        JOptionPane.showMessageDialog(rootPane, "Thêm Thành Công!");
        this.dispose();
        
        new MainForm().setVisible(true);
    }//GEN-LAST:event_themSachButtonActionPerformed

    private void huyBoSachButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_huyBoSachButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_huyBoSachButtonActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton huyBoSachButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField maTLBaoTF;
    private javax.swing.JTextField ngayPhatHanhBaoTF;
    private javax.swing.JTextField soBanPhatHanhBaoTF;
    private javax.swing.JTextField tenNSBBaoTF;
    private javax.swing.JButton themSachButton;
    // End of variables declaration//GEN-END:variables
}
