package BookManagement;

import javax.swing.JOptionPane;

/**
 *
 * @author Quốc Hùng
 */
public class AddNewTC extends javax.swing.JFrame {
    FunctionHandling handle;
    /**
     * Creates new form AddNewTL
     */
    public AddNewTC() {
        initComponents();
        setLocationRelativeTo(null);
        
        handle = new FunctionHandling();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        themTCButton = new javax.swing.JButton();
        maTLTCTF = new javax.swing.JTextField();
        huyBoTCButton = new javax.swing.JButton();
        tenNSBTCTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        soBanPhatHanhTCTF = new javax.swing.JTextField();
        soPhatHanhTCTF = new javax.swing.JTextField();
        thangPhatHanhTCTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Mã Tài Liệu:");

        jLabel3.setText("Số bản Phát Hành:");

        jLabel4.setText("Tên Nhà Xuất Bản:");

        jLabel5.setText("Số Phát Hành:");

        jLabel6.setText("Tháng Phát Hành:");

        themTCButton.setText("Thêm");
        themTCButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themTCButtonActionPerformed(evt);
            }
        });

        huyBoTCButton.setText("Huỷ Bỏ");
        huyBoTCButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                huyBoTCButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thêm mới");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(themTCButton)
                .addGap(46, 46, 46)
                .addComponent(huyBoTCButton)
                .addGap(16, 16, 16))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(thangPhatHanhTCTF)
                            .addComponent(soPhatHanhTCTF)
                            .addComponent(maTLTCTF)
                            .addComponent(tenNSBTCTF)
                            .addComponent(soBanPhatHanhTCTF, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maTLTCTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tenNSBTCTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(soBanPhatHanhTCTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(soPhatHanhTCTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(thangPhatHanhTCTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(themTCButton)
                    .addComponent(huyBoTCButton))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void themTCButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        if(maTLTCTF.getText().equals("") ||
            tenNSBTCTF.getText().equals("") ||
            soBanPhatHanhTCTF.getText().equals("") ||
            soPhatHanhTCTF.getText().equals("") ||
            thangPhatHanhTCTF.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "bạn cần nhập tất cả các trường!",
                "Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }

        for(TapChi tc : handle.GetDataTapChi()) {
            if(maTLTCTF.getText().equals(tc.getMaTaiLieu())) {
                JOptionPane.showMessageDialog(rootPane, "Mã tài liệu này hiện đã tồn tại!! ",
                    "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

        TapChi tc = new TapChi();
        tc.setMaTaiLieu(maTLTCTF.getText());
        tc.setSoBanPhatHanh(Integer.valueOf(soBanPhatHanhTCTF.getText()));
        tc.setTenNSB(tenNSBTCTF.getText());
        tc.setSoPhatHanh(soPhatHanhTCTF.getText());
        tc.setThangPhatHanh(Integer.valueOf(thangPhatHanhTCTF.getText()));

        handle.AddNewTC(tc);

        JOptionPane.showMessageDialog(rootPane, "Thêm Thành Công!");
        this.dispose();
        
        new MainForm().setVisible(true);
    }                                            

    private void huyBoTCButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        this.dispose();
    }                                             

    

    // Variables declaration - do not modify                     
    private javax.swing.JButton huyBoTCButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField maTLTCTF;
    private javax.swing.JTextField soBanPhatHanhTCTF;
    private javax.swing.JTextField soPhatHanhTCTF;
    private javax.swing.JTextField tenNSBTCTF;
    private javax.swing.JTextField thangPhatHanhTCTF;
    private javax.swing.JButton themTCButton;
    // End of variables declaration                   
}
